sudo: required
services:
  - docker

before_install:
  - docker build -t roeldijkstra/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true roeldijkstra/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "react-docker"
  env: "React-docker-env"
  bucket_name: "elasticbeanstalk-eu-west-1-925112994528"
  bucket_path: "react-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY